"""Highscores

Revision ID: 7c4188842f37
Revises: 
Create Date: 2019-05-31 15:28:11.359636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4188842f37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('solution', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_highscore_score'), 'highscore', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_highscore_score'), table_name='highscore')
    op.drop_table('highscore')
    # ### end Alembic commands ###
